services:
  # Backend service
  server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    volumes:
      - document-data:/app/documents
    restart: unless-stopped
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:5000/api/documents"]
      interval: 30s
      timeout: 10s
      retries: 3
    
  # Frontend service
  client:
    build:
      context: .
      dockerfile: docker/client.Dockerfile
    ports:
      - "80:80"
    depends_on:
      server:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  document-data:
    driver: local